name: case-opener

services:
  case-opener:
    container_name: case-opener
    build:
      context: ..
      dockerfile: Dockerfile
    image: case-opener
    env_file:
      - ../.dev.env
    environment:
      PG__HOST: case-opener-pg
      PG__PORT: "5432"
    ports:
      - "${APP_PORT}:8003"
    command: "./.venv/bin/uvicorn bootstrap.app:create_app --host 0.0.0.0 --port 8003 --factory"
    networks:
      - backend

networks:
  backend:
    driver: bridge
